spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tours_and_travels
    username: root
    password: root
  data:
    rest:
      basePath: /api/v1/
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
